pipeline {
    agent any

    stages {
        stage ("Clone Project") {
            steps {
                git "https://github.com/walsm232/CT5171-DevOps-Assignment.git"
            }
        }
        stage ("Unit Test") {
            steps {
                script {
                    echo "Testing the GitHub webhook configuration"
                }
            }
        }
        stage ("Build") {
            steps {
                sh "mvn clean:clean"
                sh "mvn dependency:copy-dependencies"
                sh "mvn compiler:compile"
            }
        }
        stage ("Exec") {
            steps {
                sh "mvn exec:java"
            }
        }
    }
}